SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;
ALTER TABLE IF EXISTS ONLY public.packet_log DROP CONSTRAINT IF EXISTS packet_log_packet_id;
ALTER TABLE IF EXISTS ONLY public.packet DROP CONSTRAINT IF EXISTS packet_pkey;
ALTER TABLE IF EXISTS ONLY public.packet_log DROP CONSTRAINT IF EXISTS packet_log_pkey;
ALTER TABLE IF EXISTS ONLY public.obj_ref DROP CONSTRAINT IF EXISTS obj_ref_pkey;
ALTER TABLE IF EXISTS ONLY public.invoice DROP CONSTRAINT IF EXISTS invoice_pkey;
ALTER TABLE IF EXISTS ONLY public.file DROP CONSTRAINT IF EXISTS file_pkey;
ALTER TABLE IF EXISTS ONLY public.document DROP CONSTRAINT IF EXISTS document_pkey;
ALTER TABLE IF EXISTS ONLY public.docset DROP CONSTRAINT IF EXISTS docset_pkey;
ALTER TABLE IF EXISTS ONLY public.contract DROP CONSTRAINT IF EXISTS contract_pkey;
ALTER TABLE IF EXISTS ONLY public.construction DROP CONSTRAINT IF EXISTS construction_pkey;
ALTER TABLE IF EXISTS ONLY public.constrpart DROP CONSTRAINT IF EXISTS constrpart_pkey;
ALTER TABLE IF EXISTS ONLY public.building DROP CONSTRAINT IF EXISTS building_pkey;
ALTER TABLE IF EXISTS public.packet_log ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.packet ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.obj_ref ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.invoice ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.file ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.document ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.docset ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.contract ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.construction ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.constrpart ALTER COLUMN id DROP DEFAULT;
ALTER TABLE IF EXISTS public.building ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE IF EXISTS public.packet_log_id_seq;
DROP TABLE IF EXISTS public.packet_log;
DROP SEQUENCE IF EXISTS public.packet_id_seq;
DROP TABLE IF EXISTS public.packet;
DROP SEQUENCE IF EXISTS public.obj_ref_id_seq;
DROP TABLE IF EXISTS public.obj_ref;
DROP SEQUENCE IF EXISTS public.invoice_id_seq;
DROP TABLE IF EXISTS public.invoice;
DROP SEQUENCE IF EXISTS public.file_id_seq;
DROP TABLE IF EXISTS public.file;
DROP SEQUENCE IF EXISTS public.document_id_seq;
DROP TABLE IF EXISTS public.document;
DROP SEQUENCE IF EXISTS public.docset_id_seq;
DROP TABLE IF EXISTS public.docset;
DROP SEQUENCE IF EXISTS public.contract_id_seq;
DROP TABLE IF EXISTS public.contract;
DROP SEQUENCE IF EXISTS public.construction_id_seq;
DROP TABLE IF EXISTS public.construction;
DROP SEQUENCE IF EXISTS public.constrpart_id_seq;
DROP TABLE IF EXISTS public.constrpart;
DROP SEQUENCE IF EXISTS public.building_id_seq;
DROP TABLE IF EXISTS public.building;

